project_root: '${PROJECT_ROOT}'

config: '${PROJECT_ROOT}/config'
secrets: '${PROJECT_ROOT}/config/secrets'

bronze: '${PROJECT_ROOT}/data/bronze'
silver: '${PROJECT_ROOT}/data/silver'
gold: '${PROJECT_ROOT}/data/gold'
archive: '${PROJECT_ROOT}/data/archive'

lib: '${PROJECT_ROOT}/lib'
jars: '${PROJECT_ROOT}/lib/jars'
downloads: '${PROJECT_ROOT}/lib/downloads'

logs: '${PROJECT_ROOT}/logs'

models: '${PROJECT_ROOT}/models'

notebooks: '${PROJECT_ROOT}/notebooks'

scripts: '${PROJECT_ROOT}/scripts'

extract: '${PROJECT_ROOT}/src/extract'
load: '${PROJECT_ROOT}/src/load'
transform: '${PROJECT_ROOT}/src/transform'
utils: '${PROJECT_ROOT}/src/utils'

tests: '${PROJECT_ROOT}/tests'
bronze_data: "${}/bronze"

landing: '/landing-data'